on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Install Packages
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y build-essential libicu-dev unixodbc unixodbc-dev
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Unit Tests
      run: go test -v ./stmt
    - name: Build with "most"
      run: ./most.sh -v
    - name: Shell Tests
      run: |
        rm -f test.db
        go run testcli.go
