on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      cassandra:
        image: usql/cassandra
      postgres:
        image: usql/postgres
        env:
          POSTGRES_PASSWORD: P4ssw0rd
      mysql:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: P4ssw0rd
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_PID: Express
          SA_PASSWORD: Adm1nP@ssw0rd
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Install Packages
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y build-essential libicu-dev unixodbc unixodbc-dev
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Unit Tests
      run: go test -v ./stmt
    - name: Build with "most"
      run: ./most.sh -v
    - name: Shell Tests
      run: |
        rm -f *.db
        go run testcli.go
