on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Install Packages
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y  build-essential libicu-dev unixodbc unixodbc-dev expect
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Unit Tests
      run: go test -v ./stmt
    - name: Build with "most"
      run: ./most.sh -v
    - name: Shell Tests
      run: |
        rm -f test.db
        export TERM=xterm-256color
        ./usql file://test.db -c 'create table author (a text, b text);'
        ./usql file://test.db -c 'select * from author;'
